### ISSUE TITLE
In listener broadcast back job hanging on CURL Error

### ISSUE THREAD

**Issue by prdip** [laravel/reverb#200]
### Reverb Version

1.0.0 beta-10

### Laravel Version

11.0

### PHP Version

8.2.7

### Description

I've implemented the listener and that works great but now I'm trying to broadcast back again but the job is hanging on an curl request for which I have no clue where or why it is making a curl request. When I broadcast the same event in a command it works fine. Does anyone have a idea?

Pusher error: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:8082/apps/899713/events?auth_key=n9djupsbzokvzk9et2zs&auth_timestamp=1716000501&auth_version=1.0&body_md5=df83fae487fd3b9a6267a60d18b3302f&auth_signature=c04c6559809aabf44c7c260df43e9e81862da2f213d30de063295c1669ef6000   

![Screenshot from 2024-05-18 08-19-42](https://github.com/laravel/reverb/assets/25522275/63079979-8221-4646-8495-08ff85e67c23)

Received message from client 

![Screenshot from 2024-05-18 08-20-47](https://github.com/laravel/reverb/assets/25522275/50fd32de-2c03-4879-8d6f-f69ee0cc333f)

but it taking 30 seconds to broadcast , if i trigger broadcast event by command or by http request then it immedietly reflect in client 

### Steps To Reproduce

Create message listener using (MessageReceived $event) 
trigger  broadcast event in same listener handle method code

It takes 30 second to receive the broadcasted message in client

Also when i trigger the broadcast using command with the same AlertTrigger event it immediatly reflect in client, But all broadcasting events hang on till this above curl error message displayed in reverb debugger 

![screenshot](https://github.com/laravel/reverb/assets/25522275/ab4c2e18-d1dd-4ece-a4a3-f2bee893758b)

When i received message in client after 30 second , first it shows 4200 message format errro & then message is being received

**Comment by swapnil15021997** [comment]
Reverb Version
@beta

Laravel Version
11.0

PHP Version
8.2.7

Description

I've implemented the listener and that's working great but now I'm trying to broadcast back again but there is slight 20 to 30 seconds delay to broadcast and listen to frontend. Does anyone have a idea?

![issues](https://github.com/laravel/reverb/assets/117801866/c167468a-122b-479e-8abc-70d13d665690)

**Comment by njzabala** [comment]
Your `QUEUE_CONNECTION` should not be sync and your broadcasting should implement `ShouldQueue` interface.

**Comment by prdip** [comment]
> Your `QUEUE_CONNECTION` should not be sync and your broadcasting should implement `ShouldQueue` interface.


Yes

Queue connection is database

And i have tried should queue interface as well still getting same issue


During message receive broadcasting

**Comment by Atmden** [comment]
Hi all!
I have the same problem!
I can't immediately send an event to another channel.
I want to receive an event from the client to trigger another event that will send a message to another channel. If I do this through a queue, everything works. If I try to send it immediately (implements ShouldBroadcastNow), I get a curl timeout error.

**Comment by njzabala** [comment]
@Atmden  Reverb uses ReactPHP. It shouldn't be blocked by any resource based transaction which is why you should use `ShouldBroadcast` instead of `ShouldBroadcastNow` and run the artisan command `queue:work`

**Comment by prdip** [comment]
> @Atmden Reverb uses ReactPHP. It shouldn't be blocked by any resource based transaction which is why you should use `ShouldBroadcast` instead of `ShouldBroadcastNow` and run the artisan command `queue:work`

Yes it’s working using queue:work


But how can we manage it using direct should broadcast 


As of now delivering reply message took delay. Is there any other way to broadcast it immediately 


?

**Comment by njzabala** [comment]
@prdip `queue:work` has parameter sleep `--sleep`. Its default is 3 seconds and you can change it to 0. I don't advise changing it to 0 since it triggers the queue always so it might be high on resource usage

**Comment by Atmden** [comment]
I solved my problem. I hope it helps others too. In the service where I process the event, I used ChannelManager.
Here is a small part of the code
```
    use Laravel\Reverb\Protocols\Pusher\Contracts\ChannelManager;

    public function __construct(ChannelManager $channelManager)
    {
        $this->channelManager = $channelManager;
    }

    public function eventHandle()
    {
        // .... different code
        
        $response = [
            "event" => "my-event",
            "channel" => "my-channel",
            "data" => [ // My data
                "success" => true,
                "message" => "......",
            ]
        ];
        $orderChannel = $this->channelManager->find('<channel name>');
        if (!empty($orderChannel)) {
            $orderChannel->broadcast($response);
        }
    }
```

**Comment by prdip** [comment]
> I solved my problem. I hope it helps others too. In the service where I process the event, I used ChannelManager. Here is a small part of the code
> 
> ```
>     use Laravel\Reverb\Protocols\Pusher\Contracts\ChannelManager;
> 
>     public function __construct(ChannelManager $channelManager)
>     {
>         $this->channelManager = $channelManager;
>     }
> 
>     public function eventHandle()
>     {
>         // .... different code
>         
>         $response = [
>             "event" => "my-event",
>             "channel" => "my-channel",
>             "data" => [ // My data
>                 "success" => true,
>                 "message" => "......",
>             ]
>         ];
>         $orderChannel = $this->channelManager->find('<channel name>');
>         if (!empty($orderChannel)) {
>             $orderChannel->broadcast($response);
>         }
>     }
> ```

Will this work without QUEUE ? Immediate broadcast

**Comment by prdip** [comment]
> @prdip `queue:work` has parameter sleep `--sleep`. Its default is 3 seconds and you can change it to 0. I don't advise changing it to 0 since it triggers the queue always so it might be high on resource usage

Thanks @njzabala 

Queue already consume lots of cpu usage & reverb also high cpu dependent.

How can we achieve superfast broadcast delivery without queue , if not then what should we keep in mind while building real time bidirectional app using reverb !

**Comment by Atmden** [comment]
> Will this work without QUEUE ? Immediate broadcast
@prdip 
Yes! Try it
It's the same if I did
`...connection->send(json_encode($response));`

**Comment by prdip** [comment]
> eventHandle

Where did you manage this 


in event listener or direct event ?

**Comment by Atmden** [comment]
> > eventHandle
> 
> Where did you manage this
> 
> in event listener or direct event ?

I'm using a listener. Which listens to MessageReceived.
My listener receives a message from the client application. I determine the ownership of this message and call the method in my service. And in the service I do an immediate sending of another message to another channel. I have a lot of different incoming messages and therefore I moved their processing into a separate service; you can use immediate sending directly in the listener

**Comment by njzabala** [comment]
If the issue is solved, I suggest closing the issue.

**Comment by Atmden** [comment]
@njzabala 
If there is such a possibility, you need to add a plan for implementing this functionality to the package so as not to make crutches

**Comment by njzabala** [comment]
@Atmden Sorry. I'm not a maintainer of reverb. I just helped with what I currently know.

**Comment by joedixon** [comment]
You will need to queue the listener or broadcast directly or broadcast to the channel directly otherwise you will block the event loop.

If you don't do that, when you catch the event, any work you do blocks the loop from processing more connections or messages. As such, if you try to broadcast a mesage syncronously, the loop cannot process it so you end up in a deadlock.

**Comment by prdip** [comment]
@joedixon 

Is @Atmden's Channel Manager the most effective way to broadcast instantly without a queue, then?

**Comment by Atmden** [comment]
@joedixon 

I didn't clearly understand your answer.
At the moment the application is just being written and there is no real load. If you check on test accounts, everything works as it should.
But did I understand your answer correctly that if I use the ChannelManager in production to immediately send messages to a channel, I will encounter a waiting problem, new incoming messages will not be processed until the outgoing one is sent?

**Comment by joedixon** [comment]
Using the ChannelManager should be fine as you are already in the context of the event loop. The issue with broadcasting (without queuing) is because you are making an HTTP request to the WebSocket server, which can't accept the request until the current process is complete. Of course, the current process cannot complete as it's waiting on the HTTP request so you end up in deadlock.

**Comment by mauricecalhoun** [comment]
@Atmden How were you able to find the channel by name when that information did not exist at the time? Could I see more of the code to understand how this is being done?
