### ISSUE TITLE
Windows not supported (yet)?

### ISSUE THREAD

**Issue by kayschima** [laravel/reverb#65]
### Reverb Version

v1.0.0-beta2

### Laravel Version

11.0.2

### PHP Version

8.3.2

### Description

When I install Reverb I get the error message:

```
Would you like to install and build the Node dependencies required for broadcasting? (yes/no) [yes]
❯

   INFO  Installing and building Node dependencies.


   Symfony\Component\Process\Exception\RuntimeException

  TTY mode is not supported on Windows platform.

  at vendor\symfony\process\Process.php:1013
    1009▕      */
    1010▕     public function setTty(bool $tty): static
    1011▕     {
    1012▕         if ('\\' === \DIRECTORY_SEPARATOR && $tty) {
  ➜ 1013▕             throw new RuntimeException('TTY mode is not supported on Windows platform.');
    1014▕         }
    1015▕
    1016▕         if ($tty && !self::isTtySupported()) {
    1017▕             throw new RuntimeException('TTY mode requires /dev/tty to be read/writable.');
```

Is Windows not supported for Reverb?

### Steps To Reproduce

```
laravel new laravel11
php artisan install:broadcasting
```

**Comment by kayschima** [comment]
Addition: I do not use WSL on Windows.

**Comment by OussamaMater** [comment]
I don't think it is related to Reverb itself. The `install:broadcasting` command is included with Laravel 11, not Reverb. When running it, TTY is required (check [here](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Console/BroadcastingInstallCommand.php#L173)), but it is not supported in Windows. You can manually install npm dependencies since Reverb was already installed if you reached that part.
```bash
npm install --save-dev laravel-echo pusher-js
npm run build
```

The command is just for convenience. You can check what it is doing and manually perform the steps while the issue is being resolved for Windows.
https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Console/BroadcastingInstallCommand.php

**Comment by ThibautGobert** [comment]
I am also on Windows and I can't start it, I get this error :

` Undefined constant "Laravel\Reverb\Servers\Reverb\Console\Commands\SIGINT"`

`Laravel\Reverb\Servers\Reverb\Console\Commands\StartServer::getSubscribedSignals()`

**Comment by kayschima** [comment]
@OussamaMater : I guess you're right.

So, this should be either fixed in the Laravel repository or be mentioned in the documentation.

**Comment by njzabala** [comment]
@ThibautGobert: It is related with PCNTL PHP extension which is currently unavailable for Windows

[https://stackoverflow.com/questions/78150154/issue-starting-laravel-reverb-server-on-windows-undefined-constant-error](url)

**Comment by OussamaMater** [comment]
@kayschima Yes exactly!

**Comment by driesvints** [comment]
Right now we have no plans for non WSL versions of Windows sorry.

**Comment by driesvints** [comment]
Seems someone is actually working on a fix: https://github.com/laravel/framework/pull/50495

**Comment by driesvints** [comment]
Re-opening this for now.

**Comment by driesvints** [comment]
We released https://github.com/laravel/framework/pull/50519 in v11.0.5 so please upgrade. Thanks.

**Comment by kayschima** [comment]
Installation works fine now with 11.0.5. The SIGINT error is still there on startup of the service.

**Comment by jbarreraballestas** [comment]
Not solved for laravel 10, need to wait?
[https://github.com/laravel/reverb/issues/74](https://github.com/laravel/reverb/issues/74)

**Comment by driesvints** [comment]
Aaaah I thought it was just the issue within framework itself. Seems like a PR was made so we'll get this in soon.

**Comment by playerro** [comment]
Any updates?
